use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{notifications, preferences, quick_pane, recovery};
    use crate::modules::{gtd, rem};

    Builder::<tauri::Wry>::new().commands(collect_commands![
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::show_main_window,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        gtd::commands::gtd_get_tree,
        gtd::commands::gtd_create_group,
        gtd::commands::gtd_rename_group,
        gtd::commands::gtd_move_group,
        gtd::commands::gtd_delete_group,
        gtd::commands::gtd_register_document,
        gtd::commands::gtd_rename_document,
        gtd::commands::gtd_move_document,
        gtd::commands::gtd_delete_document,
        gtd::commands::gtd_preview_import_path,
        gtd::commands::gtd_read_document,
        gtd::commands::gtd_save_document,
        rem::commands::rem_get_state,
        rem::commands::rem_create_reminder,
        rem::commands::rem_update_reminder,
        rem::commands::rem_toggle_reminder,
        rem::commands::rem_delete_reminder,
        rem::commands::rem_update_log_status,
        rem::commands::rem_update_log_note,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
///
/// Failure is non-fatal: a bundled debug build launched from Finder has a
/// read-only working directory, so the relative export path is unwritable.
/// Crashing the whole app there is unacceptable, so we log and continue.
pub fn export_ts_bindings() {
    if let Err(e) = generate_bindings().export(
        specta_typescript::Typescript::default()
            .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
        "../src/lib/bindings.ts",
    ) {
        log::warn!("Skipped exporting TypeScript bindings: {e}");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
